"""empty message

Revision ID: e06848138ff6
Revises: 8ed7775249e9
Create Date: 2024-06-13 17:12:14.268947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06848138ff6'
down_revision = '8ed7775249e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.drop_constraint('greeting_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('greeting_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
